/*
 * Created on 25 sep 2015 ( Time 16:31:02 )
 * Generated by Máximo
 */
package com.drive.bean;

import java.io.Serializable;

import javax.validation.constraints.*;


public class Filter implements Serializable {

    private static final long serialVersionUID = 1L;

  
    private String field;


    private String value;


	public String getField() {
		return field;
	}


	public void setField(String field) {
		this.field = field;
	}


	public String getValue() {
		return value;
	}


	public void setValue(String value) {
		this.value = value;
	}



 

}
