/*
 * Created on 14 sep 2015 ( Time 20:17:55 )
 * Generated by Máximo
 */
package com.drive.bean;

import java.io.Serializable;

import javax.persistence.Cacheable;
import javax.validation.constraints.*;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

public class User implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private Integer id;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Size( max = 150 )
    private String name;

    @Size( max = 150 )
    private String phone;

    @Size( max = 150 )
    private String company;

    @Size( max = 150 )
    private String iban;


   
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }

    public Integer getId() {
        return this.id;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(name);
        sb.append("|");
        sb.append(phone);
        sb.append("|");
        sb.append(company);
        sb.append("|");
        sb.append(iban);
        sb.append("|");
       
        return sb.toString(); 
    }





		public String getName() {
			return name;
		}





		public void setName(String name) {
			this.name = name;
		}





		public String getPhone() {
			return phone;
		}





		public void setPhone(String phone) {
			this.phone = phone;
		}





		public String getCompany() {
			return company;
		}





		public void setCompany(String company) {
			this.company = company;
		}





		public String getIban() {
			return iban;
		}





		public void setIban(String iban) {
			this.iban = iban;
		}





		public static long getSerialversionuid() {
			return serialVersionUID;
		} 


}

