/*
 * Created on 25 sep 2015 ( Time 16:31:03 )
 * Generated by Máximo
 */
package com.drive.web.common;

public enum MessageType {
	
	SUCCESS,
	INFO,
	WARNING,
	DANGER;
	
	public String getCss() {
		return name().toLowerCase();
	}
	
}
