/*
 * Created on 25 sep 2015 ( Time 16:31:03 )
 * Generated by Máximo
 */
package com.drive.web.listitem;

import com.drive.web.common.ListItem;

public class FiltersListItem implements ListItem {

	private final String value ;
	private final String label ;
	
	public FiltersListItem(String value, String label) {
		super();

		this.value = ""
			 + value
		;

		//TODO : Define here the attributes to be displayed as the label
		this.label = label;
	}

	@Override
	public String getValue() {
		return value;
	}

	@Override
	public String getLabel() {
		return label;
	}

}
