/*
 * Created on 20 nov 2015 ( Time 20:44:41 )
 * Generated by Máximo
 */
package com.drive.web.listitem;

import com.drive.bean.User;
import com.drive.web.common.ListItem;

public class UserListItem implements ListItem {

	private final String value ;
	private final String label ;
	
	public UserListItem(User user) {
		super();

		this.value = ""
			 + user.getId()
		;

		//TODO : Define here the attributes to be displayed as the label
		this.label = user.toString();
	}

	@Override
	public String getValue() {
		return value;
	}

	@Override
	public String getLabel() {
		return label;
	}

}
